[target.mipsel-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-Wl,-dynamic-linker,/opt/lib/ld.so.1",
    "-C", "link-arg=-Wl,-rpath,/opt/lib",
    "-C", "link-arg=-no-pie",   # ← 关键！强制输出 executable 而不是 shared object
]

[target.mips-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-Wl,-dynamic-linker,/opt/lib/ld.so.1",
    "-C", "link-arg=-Wl,-rpath,/opt/lib",
    "-C", "link-arg=-no-pie",   
]

[target.mipsel-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-no-pie",
]