name: Build Releases
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch: # <--- 添加这一行

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mips-entware:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 0
    strategy:
      matrix:
        target:
          - mips-unknown-linux-musl

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - name: Add rust target
        run: rustup target add ${{ matrix.target }} || true
      - name: Install cargo-zigbuild
        run: pip install ziglang && cargo install cargo-zigbuild
      - name: Build with cargo-zigbuild
        run: |
          cargo zigbuild --release \
            --target ${{ matrix.target }} \
            -Z build-std=std,panic_abort 、
            --zig-abi mipsel-linux.1.1.82-musleabi
      - name: Rename artifacts and compress
        run: |
          cd target/${{ matrix.target }}/release
          mv client phantun_client
          mv server phantun_server
          zip phantun_${{ matrix.target }}_nightly.zip phantun_client phantun_server

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/*.zip
          prerelease: ${{ contains(github.ref, '-') }}
